### ISSUE TITLE
exception in thread "main"

### ISSUE THREAD

**Issue by talpa25** [yeastrc/proxl-import-plink2#1]
Hi,
unfortunately i get an exception trying to run the converter for pLink2:
which java version do you recommend?

Loading search parameters... Exception in thread "main" java.lang.reflect.Invoca
tionTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:58)
Caused by: java.io.FileNotFoundException: C:\*\Documents\pLink\pLink_t
ask_2018.07.13.13.03.30_mE_BMOE (Access is denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at org.yeastrc.proxl.xml.plink2.ini.ParsedINIFile.<init>(ParsedINIFile.j
ava:45)
        at org.yeastrc.proxl.xml.plink2.reader.PLinkSearchParametersLoader.getPL
inkSearch(PLinkSearchParametersLoader.java:46)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.convertSearch(MainProgr
am.java:42)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.main(MainProgram.java:9
0)
        ... 5 more

**Comment by talpa25** [comment]
i changed to admin right command prompt

C:\*\Documents\pLink>java -jar plink2toProxlXML.jar -p C:\*\
Documents\pLink\pLink_task_2018.07.26.mE_Pea_BS3\pLink_task_2018.07.26.mE_Pea_BS
3.plink -o C:\*\Documents\pLink\output.proxml.xml
Loading search parameters... Done.
Loading search results... Done.
Writing proxl XML... Exception in thread "main" java.lang.reflect.InvocationTarg
etException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:58)
Caused by: java.lang.NullPointerException
        at java.io.File.<init>(Unknown Source)
        at org.yeastrc.proxl.xml.plink2.builder.XMLBuilder.buildAndSaveXML(XMLBu
ilder.java:100)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.convertSearch(MainProgr
am.java:51)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.main(MainProgram.java:9
0)
        ... 5 more

C:\*\Documents\pLink>

**Comment by mriffle** [comment]
@talpa25, thanks for your issue report.

It looks like this is caused by not including the -f parameter, which specifies the location of the FASTA file used for the search. I.e., -f c:\fastas\myFasta.fasta

I will update the program to improve the check that all necessary parameters are specified, sorry about that.

Mike

**Comment by mriffle** [comment]
I've just released version 1.0.4 on the releases page that includes runtime checking that all required params are specified, and will now report the version of the converter you are running.

**Comment by talpa25** [comment]
i checked the new version with all the options, but it failed again :/

C:\Users\massy\Documents\pLink>java -jar plink2toProxlXML.jar -p C:\Users\massy\
Documents\pLink\pLink_task_2018.07.26.mE_Pea_BS3 -o C:\MassSpec\DATA\C:\MassSpec
\DATA\20180704_mE_Pea_XL-MS\mysearchpLink.proxml.xml -f C:\MassSpec\DATA\2018070
4_mE_Pea_XL-MS\20180704_mE_XL-MS_Ident_Roman_uniprot5new\proteins_mE_XL-MS_con_c
omb_rever.fasta -r C:\users\massy\Documents\plink\pLink_task_2018.07.26.mE_Pea_B
S3\reports
pLink 2.x to proxl XML converter
Author: Michael Riffle <mriffle@uw.edu>
See: https://github.com/yeastrc/proxl-import-plink2
Version: 1.0.4

Loading search parameters... Exception in thread "main" java.lang.reflect.Invoca
tionTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:58)
Caused by: java.io.FileNotFoundException: C:\Users\massy\Documents\pLink\pLink_t
ask_2018.07.26.mE_Pea_BS3 (Access is denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at org.yeastrc.proxl.xml.plink2.ini.ParsedINIFile.<init>(ParsedINIFile.j
ava:45)
        at org.yeastrc.proxl.xml.plink2.reader.PLinkSearchParametersLoader.getPL
inkSearch(PLinkSearchParametersLoader.java:46)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.convertSearch(MainProgr
am.java:43)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.main(MainProgram.java:1
02)
        ... 5 more

the *.plink file is in the given -p folder

**Comment by danjasuw** [comment]
This line in the error message explains what the error is:
Caused by: java.io.FileNotFoundException: C:\Users\massy\Documents\pLink\pLink_task_2018.07.26.mE_Pea_BS3 (Access is denied)

**Comment by mriffle** [comment]
Hi, also, the -p option should point to a specific file, not the directory containing that file.

**Comment by talpa25** [comment]
ok, next try:
C:\Users\massy\Documents\pLink>java -jar plink2toProxlXML.jar -p C:\Users\massy\
Documents\pLink\pLink_task_2018.07.26.mE_Pea_BS3\pLink_task_2018.07.26.mE_Pea_BS
3.plink -o C:\massspec\data\20180704_mE_Pea_XL-MS\mysearchpLink.proxml.xml -f C:
\MassSpec\DATA\20180704_mE_Pea_XL-MS\20180704_mE_XL-MS_Ident_Roman_uniprot5new\p
roteins_mE_XL-MS_con_comb_rever.fasta -r C:\users\massy\documents\plink\pLink_ta
sk_2018.07.26.mE_Pea_BS3\reports
pLink 2.x to proxl XML converter
Author: Michael Riffle <mriffle@uw.edu>
See: https://github.com/yeastrc/proxl-import-plink2
Version: 1.0.4

Loading search parameters... Done.
Loading search results... Exception in thread "main" java.lang.reflect.Invocatio
nTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:58)
Caused by: java.lang.Exception: can not find data directory: C:\users\massy\docu
ments\plink\pLink_task_2018.07.26.mE_Pea_BS3\reports\reports
        at org.yeastrc.proxl.xml.plink2.reader.PLinkResultsLoader.getResults(PLi
nkResultsLoader.java:57)
        at org.yeastrc.proxl.xml.plink2.reader.PLinkResultsLoader.getAllResults(
PLinkResultsLoader.java:103)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.convertSearch(MainProgr
am.java:47)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.main(MainProgram.java:1
02)
        ... 5 more

C:\Users\massy\Documents\pLink>java -jar plink2toProxlXML.jar -p C:\Users\massy\
Documents\pLink\pLink_task_2018.07.26.mE_Pea_BS3\pLink_task_2018.07.26.mE_Pea_BS
3.plink -o C:\massspec\data\20180704_mE_Pea_XL-MS\mysearchpLink.proxml.xml -f C:
\MassSpec\DATA\20180704_mE_Pea_XL-MS\20180704_mE_XL-MS_Ident_Roman_uniprot5new\p
roteins_mE_XL-MS_con_comb_rever.fasta -r C:\users\massy\documents\plink\pLink_ta
sk_2018.07.26.mE_Pea_BS3
pLink 2.x to proxl XML converter
Author: Michael Riffle <mriffle@uw.edu>
See: https://github.com/yeastrc/proxl-import-plink2
Version: 1.0.4

Loading search parameters... Done.
Loading search results... Warning: Could not load cross-linked data.
Reason: can not find data file: C:\users\massy\documents\plink\pLink_task_2018.0
7.26.mE_Pea_BS3\reports\20180704_mE_XL-MS_con_2018.07.30.filtered_cross-linked_s
pectra.csv
Skipping.
Warning: Could not load loop-linked data.
Reason: can not find data file: C:\users\massy\documents\plink\pLink_task_2018.0
7.26.mE_Pea_BS3\reports\20180704_mE_XL-MS_con_2018.07.30.filtered_loop-linked_sp
ectra.csv
Skipping.
Warning: Could not load mono-linked data.
Reason: can not find data file: C:\users\massy\documents\plink\pLink_task_2018.0
7.26.mE_Pea_BS3\reports\20180704_mE_XL-MS_con_2018.07.30.filtered_mono-linked_sp
ectra.csv
Skipping.
Warning: Could not load regular data.
Reason: can not find data file: C:\users\massy\documents\plink\pLink_task_2018.0
7.26.mE_Pea_BS3\reports\20180704_mE_XL-MS_con_2018.07.30.filtered_regular_spectr
a.csv
Skipping.
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:58)
Caused by: java.lang.Exception: Could not find any data at location specified...

Location: C:\Users\massy\Documents\pLink\\pLink_task_2018.07.26.mE_Pea_BS3\
        at org.yeastrc.proxl.xml.plink2.reader.PLinkResultsLoader.getAllResults(
PLinkResultsLoader.java:138)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.convertSearch(MainProgr
am.java:47)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.main(MainProgram.java:1
02)
        ... 5 more

C:\Users\massy\Documents\pLink>java -jar plink2toProxlXML.jar -p C:\Users\massy\
Documents\pLink\pLink_task_2018.07.26.mE_Pea_BS3\pLink_task_2018.07.26.mE_Pea_BS
3.plink -o C:\massspec\data\20180704_mE_Pea_XL-MS\mysearchpLink.proxml.xml -f C:
\MassSpec\DATA\20180704_mE_Pea_XL-MS\20180704_mE_XL-MS_Ident_Roman_uniprot5new\p
roteins_mE_XL-MS_con_comb_rever.fasta -r C:\users\massy\documents\plink\pLink_ta
sk_2018.07.26.mE_Pea_BS3\reports
pLink 2.x to proxl XML converter
Author: Michael Riffle <mriffle@uw.edu>
See: https://github.com/yeastrc/proxl-import-plink2
Version: 1.0.4

Loading search parameters... Done.
Loading search results... Exception in thread "main" java.lang.reflect.Invocatio
nTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoa
der.java:58)
Caused by: java.lang.Exception: can not find data directory: C:\users\massy\docu
ments\plink\pLink_task_2018.07.26.mE_Pea_BS3\reports\reports
        at org.yeastrc.proxl.xml.plink2.reader.PLinkResultsLoader.getResults(PLi
nkResultsLoader.java:57)
        at org.yeastrc.proxl.xml.plink2.reader.PLinkResultsLoader.getAllResults(
PLinkResultsLoader.java:103)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.convertSearch(MainProgr
am.java:47)
        at org.yeastrc.proxl.xml.plink2.main.MainProgram.main(MainProgram.java:1
02)
        ... 5 more

**Comment by mriffle** [comment]
Goodness, I need to put in better error reporting! I'll do that soon.

In the meantime, I think we can figure this out. Thanks for your patience.

Can you show me the directory listing of this directory: C:\users\massy\documents\plink\pLink_ta
sk_2018.07.26.mE_Pea_BS3\reports ?

**Comment by talpa25** [comment]
20:04            htmls
 20:04            images
 18:30            reports
 19:02            tmps
 20:04        367 20180717_mE_400mM_BS3_1_HCDFT.regular.plabel
 20:04        400 20180717_mE_400mM_BS3_2_HCDFT.cross-linked.BS3.plabel
 20:04        381 20180717_mE_400mM_BS3_2_HCDFT.mono-linked.BS3.plabel
 20:04        371 20180717_mE_400mM_BS3_2_HCDFT.regular.plabel
 20:04        376 20180717_mE_400mM_BS3_3_HCDFT.regular.plabel
 20:04        652 20180717_mE_solub_400mM_BS3_2_HCDFT.mono-linked.BS3.plabel
 20:04        660 20180717_mE_solub_400mM_BS3_3_HCDFT.mono-linked.BS3.plabel
 20:04        383 20180717_mE_solub_400mM_BS3_3_HCDFT.regular.plabel
 19:03       4870 20180724_mE_3M_BS3_1_HCDFT.cross-linked.BS3.plabel
 19:03      20416 20180724_mE_3M_BS3_1_HCDFT.loop-linked.BS3.plabel
 19:03      66968 20180724_mE_3M_BS3_1_HCDFT.mono-linked.BS3.plabel
 19:03     319735 20180724_mE_3M_BS3_1_HCDFT.regular.plabel
 19:03       4342 20180724_mE_3M_BS3_2_HCDFT.cross-linked.BS3.plabel
 19:03      27293 20180724_mE_3M_BS3_2_HCDFT.loop-linked.BS3.plabel
 19:03      81103 20180724_mE_3M_BS3_2_HCDFT.mono-linked.BS3.plabel
 19:03     378997 20180724_mE_3M_BS3_2_HCDFT.regular.plabel
 19:03       9419 20180724_mE_3M_BS3_3_HCDFT.cross-linked.BS3.plabel
 19:03      30792 20180724_mE_3M_BS3_3_HCDFT.loop-linked.BS3.plabel
 19:03      90201 20180724_mE_3M_BS3_3_HCDFT.mono-linked.BS3.plabel
 19:03     406695 20180724_mE_3M_BS3_3_HCDFT.regular.plabel
 19:03      13424 20180724_mE_solub_3M_BS3_1_HCDFT.cross-linked.BS3.plabel
 19:03      37269 20180724_mE_solub_3M_BS3_1_HCDFT.loop-linked.BS3.plabel
 19:03     108341 20180724_mE_solub_3M_BS3_1_HCDFT.mono-linked.BS3.plabel
 19:03     430932 20180724_mE_solub_3M_BS3_1_HCDFT.regular.plabel
 19:03      13128 20180724_mE_solub_3M_BS3_2_HCDFT.cross-linked.BS3.plabel
 19:03      40547 20180724_mE_solub_3M_BS3_2_HCDFT.loop-linked.BS3.plabel
 19:03     117701 20180724_mE_solub_3M_BS3_2_HCDFT.mono-linked.BS3.plabel
 19:03     498194 20180724_mE_solub_3M_BS3_2_HCDFT.regular.plabel
 19:03      12759 20180724_mE_solub_3M_BS3_3_HCDFT.cross-linked.BS3.plabel
 19:03      45219 20180724_mE_solub_3M_BS3_3_HCDFT.loop-linked.BS3.plabel
 19:03     111870 20180724_mE_solub_3M_BS3_3_HCDFT.mono-linked.BS3.plabel
 19:03     481822 20180724_mE_solub_3M_BS3_3_HCDFT.regular.plabel
 19:03       6328 general.html
 11:52       1687 pLink_task_2018.07.26.mE_Pea_BS3.plink
 12:32       2696 pQuant_cfg.txt

**Comment by talpa25** [comment]
i rerun plink2 in the same folder, maybe the timestamp name is the error?

**Comment by mriffle** [comment]
@talpa25 Can you show me the directory contents of the "reports" folder in that folder? For some reason the converter cannot locate expected results in that directory. Yes, I am wondering if this has to do with expected timestamps being different--and if this is the case, I need to code up a solution to that problem.

These lines show the files that the converter is looking for:

Loading search results... Warning: Could not load cross-linked data.
Reason: can not find data file: C:\users\massy\documents\plink\pLink_task_2018.0
7.26.mE_Pea_BS3\reports\20180704_mE_XL-MS_con_2018.07.30.filtered_cross-linked_s
pectra.csv
Skipping.
Warning: Could not load loop-linked data.
Reason: can not find data file: C:\users\massy\documents\plink\pLink_task_2018.0
7.26.mE_Pea_BS3\reports\20180704_mE_XL-MS_con_2018.07.30.filtered_loop-linked_sp
ectra.csv
Skipping.
Warning: Could not load mono-linked data.
Reason: can not find data file: C:\users\massy\documents\plink\pLink_task_2018.0
7.26.mE_Pea_BS3\reports\20180704_mE_XL-MS_con_2018.07.30.filtered_mono-linked_sp
ectra.csv
Skipping.
Warning: Could not load regular data.
Reason: can not find data file: C:\users\massy\documents\plink\pLink_task_2018.0
7.26.mE_Pea_BS3\reports\20180704_mE_XL-MS_con_2018.07.30.filtered_regular_spectr
a.csv
Skipping.

**Comment by talpa25** [comment]
[pLink_task_2018.08.02.DMTMM_mE_Pea_full.plink.zip](https://github.com/yeastrc/proxl-import-plink2/files/2253783/pLink_task_2018.08.02.DMTMM_mE_Pea_full.plink.zip)

This is another search of plink with the Crosslinker DMTMM. So far i cannot use it with ProXML but thats a different story. Did you checked the outputpath has two "\\" ???

The result folder zipped:
[reports.zip](https://github.com/yeastrc/proxl-import-plink2/files/2253798/reports.zip)


The further content of this directory is:
02/08/2018  13:12               397 20180704_mE_200mM_DMTMM_2_HCDFT.regular.plab
el
02/08/2018  13:12               321 20180704_mE_200mM_DMTMM_3_HCDFT.mono-linked.
DMTMM.plabel
02/08/2018  13:12               421 20180704_mE_solub_200mM_DMTMM_1_HCDFT.mono-l
inked.DMTMM.plabel
02/08/2018  13:12               326 20180717_mE_400mM_DMTMM_2_HCDFT.regular.plab
el
02/08/2018  13:12               571 20180724_mE_3M_DMTMM_1_HCDFT.cross-linked.DM
TMM.plabel
02/08/2018  13:12             4,776 20180724_mE_3M_DMTMM_1_HCDFT.loop-linked.DMT
MM.plabel
02/08/2018  13:12             1,899 20180724_mE_3M_DMTMM_1_HCDFT.mono-linked.DMT
MM.plabel
02/08/2018  13:12           109,680 20180724_mE_3M_DMTMM_1_HCDFT.regular.plabel
02/08/2018  13:12               778 20180724_mE_3M_DMTMM_2_HCDFT.cross-linked.DM
TMM.plabel
02/08/2018  13:12             5,206 20180724_mE_3M_DMTMM_2_HCDFT.loop-linked.DMT
MM.plabel
02/08/2018  13:12             1,804 20180724_mE_3M_DMTMM_2_HCDFT.mono-linked.DMT
MM.plabel
02/08/2018  13:12           118,601 20180724_mE_3M_DMTMM_2_HCDFT.regular.plabel
02/08/2018  13:12             3,442 20180724_mE_3M_DMTMM_3_HCDFT.loop-linked.DMT
MM.plabel
02/08/2018  13:12               742 20180724_mE_3M_DMTMM_3_HCDFT.mono-linked.DMT
MM.plabel
02/08/2018  13:12            53,336 20180724_mE_3M_DMTMM_3_HCDFT.regular.plabel
02/08/2018  13:12               835 20180724_mE_solub_3M_DMTMM_1_HCDFT.cross-lin
ked.DMTMM.plabel
02/08/2018  13:12            13,306 20180724_mE_solub_3M_DMTMM_1_HCDFT.loop-link
ed.DMTMM.plabel
02/08/2018  13:12             6,499 20180724_mE_solub_3M_DMTMM_1_HCDFT.mono-link
ed.DMTMM.plabel
02/08/2018  13:12           150,222 20180724_mE_solub_3M_DMTMM_1_HCDFT.regular.p
label
02/08/2018  13:12             1,436 20180724_mE_solub_3M_DMTMM_2_HCDFT.cross-lin
ked.DMTMM.plabel
02/08/2018  13:12            13,333 20180724_mE_solub_3M_DMTMM_2_HCDFT.loop-link
ed.DMTMM.plabel
02/08/2018  13:12             8,108 20180724_mE_solub_3M_DMTMM_2_HCDFT.mono-link
ed.DMTMM.plabel
02/08/2018  13:12           173,262 20180724_mE_solub_3M_DMTMM_2_HCDFT.regular.p
label
02/08/2018  13:12             1,315 20180724_mE_solub_3M_DMTMM_3_HCDFT.cross-lin
ked.DMTMM.plabel
02/08/2018  13:12            15,074 20180724_mE_solub_3M_DMTMM_3_HCDFT.loop-link
ed.DMTMM.plabel
02/08/2018  13:12             5,284 20180724_mE_solub_3M_DMTMM_3_HCDFT.mono-link
ed.DMTMM.plabel
02/08/2018  13:12           172,825 20180724_mE_solub_3M_DMTMM_3_HCDFT.regular.p
label
02/08/2018  13:12             6,314 general.html
02/08/2018  13:12    <DIR>          htmls
02/08/2018  13:12    <DIR>          images
02/08/2018  13:31             2,681 pLink_task_2018.08.02.DMTMM_mE_Pea_full.plin
k
02/08/2018  16:04               890 pLink_task_2018.08.02.DMTMM_mE_Pea_full.plin
k.zip
02/08/2018  13:31             2,681 pLink_task_2018.08.02.DMTMM_mE_Pea_full.txt.
plink
02/08/2018  13:31             3,467 pQuant_cfg.txt
02/08/2018  15:15    <DIR>          reports
02/08/2018  16:07         4,959,074 reports.zip
02/08/2018  13:12    <DIR>          tmps
              33 File(s)      5,838,906 bytes
               6 Dir(s)  44,554,199,040 bytes free

**Comment by mriffle** [comment]
@talpa25 I have released a new version that has less spammy (and more understandable) error reporting.

I was able to successfully parse the example reports directory and .plink file you included above (by changing the linker to DSS for testing). However, these aren't the same .plink and reports directory you're having trouble with, correct? Can you send me the .plink file and the directory listing (whole files aren't necessary) for the reports directory that is producing the error? I need to see what files are present to understand why the converter cannot find the files it is looking for.

I suspect the date in the "spec_title = mE_pea_cleaned_reduced_2018.08.02" line in the .plink file is not matching any files in the reports directory because those files were generated on a different date. I just need to confirm.

**Comment by mriffle** [comment]
@talpa25 Regarding the DMTMM cross-linker:

Can you send me your DMTMM line from your xlink.ini file in your pLink install directory? This should be all I need to add support for DMTMM to proxl so you can import those data. If you want to create a new issue for that, we can talk about it there.
