### ISSUE TITLE
Error with Linker Representation

### ISSUE THREAD

**Issue by lrschmitt** [yeastrc/proxl-import-plink2#3]
Hi,

I've run through this converter before with the same pLink search parameters I have now. However, I've encountered a new error that I can't figure out. When the program goes to load search parameters, I receive the following error:

Encountered an error during conversion:
Did not get ten fields in linker representation: K Q -17.027 -17.027 -17.027 -17.027 N(-1)H(-3) N(-1)H(-3) 0 0 0

As I said, I have run this converter with these identical search parameters before and this linker posed no issues. The only change is that we have updated to pLink version 2.3.9. If you have any suggestions for trouble shooting, they would be much appreciated!

**Comment by mriffle** [comment]
Hi, thanks for letting us know. I suspect you're right about the new version, we'll look into this very soon and get back you.

**Comment by mriffle** [comment]
@lrschmitt I've put v1.4.0 of the converter here: https://github.com/yeastrc/proxl-import-plink2/releases  Please let me know if this continues to give you problems!

**Comment by lrschmitt** [comment]
Looks like this fixed my problems, thank you so much for the quick reply and assistance!
